language: java
install:
  - source ~/virtualenv/python3.6/bin/activate
  - python3 -V
  - git clone https://github.com/aniehuser/senior-design-group10.git
  - cd senior-design-group10/scripts
  - ./deploy_python3.sh &
##### TODO:: edit this time after signin/signup route
  - sleep 30s
##### TODO:: remove the following lines once we have a signin/signup route #####
  - cd ../yw_website
  - echo "from django.contrib.auth.models import User; User.objects.create_superuser('niehuser', 'admin@example.com', 'pass')" | python3 manage.py shell
################################################################################
  - cd ../..
script: mvn test
jdk:
  - openjdk10
  - openjdk11
  - oraclejdk11
