language: java
before-install:
  - sudo apt-get install python3.6
install:
  - git clone https://github.com/aniehuser/senior-design-group10.git
  - cd senior-design-group10/scripts
  - ./deploy_python3.sh
script: mvn test
jdk:
  - openjdk10
  - openjdk11
  - oraclejdk11
