language: java
install:
#  - sudo add-apt-repository ppa:jonathonf/python-3.6
#  - echo
#  - sudo apt-get update
#  - sudo apt-get install python3.6

#  - wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz
#  - tar -xvf Python-3.6.3.tgz
#  - cd Python-3.6.3
#  - sudo ./configure --enable-optimizations
#  - sudo make -j8
#  - sudo make install
  - source ~/virtualenv/python3.6/bin/activate
  - python3 -V
  - git clone https://github.com/aniehuser/senior-design-group10.git
  - cd senior-design-group10/scripts
  - ./deploy_python3.sh &
##### TODO:: remove the following lines once we have a signin/signup route #####
  - cd ../yw_website
  - echo "from django.contrib.auth.models import User; User.objects.create_superuser('niehuser', 'admin@example.com', 'pass')" | python3 manage.py shell
################################################################################
  - sleep 5s
  - cd ../..
script: mvn test
jdk:
  - openjdk10
  - openjdk11
  - oraclejdk11
