language: java
install:
  - git clone https://github.com/aniehuser/senior-design-group10.git
  - cd senior-design-group10/scripts
  - python -V
  - python3 -V
  - ./deploy_python3.sh
script: mvn test
jdk:
  - openjdk10
  - openjdk11
  - oraclejdk11
